package org.camunda.community.bpmndt.platform8.strategy;

import org.camunda.community.bpmndt.model.platform8.BpmnElement;
import org.camunda.community.bpmndt.model.platform8.BpmnElementType;
import org.camunda.community.bpmndt.model.platform8.BpmnEventSupport;
import org.camunda.community.bpmndt.platform8.api.TestCaseInstanceElement.UserTaskElement;

import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeName;

import io.camunda.zeebe.model.bpmn.instance.BoundaryEvent;
import io.camunda.zeebe.model.bpmn.instance.ErrorEventDefinition;

public class JobStrategy extends DefaultHandlerStrategy {

  public JobStrategy(BpmnElement element) {
    super(element);
  }

  @Override
  public TypeName getHandlerType() {
    return USER_TASK;
  }

  @Override
  public void initHandler(MethodSpec.Builder methodBuilder) {
    super.initHandler(methodBuilder);

    if (!element.hasNext()) {
      return;
    }

    BpmnElement next = element.getNext();
    if (!next.getType().isBoundaryEvent()) {
      return;
    }

    if (next.getType() == BpmnElementType.ERROR_BOUNDARY) {
      methodBuilder.addStatement("$L.throwBpmnError($S)", literal, "error message, generated by BPMNDT");
    }
  }

  @Override
  public void initHandlerElement(MethodSpec.Builder methodBuilder) {
    methodBuilder.addCode("\n// $L: $L\n", element.getTypeName(), element.getId());
    methodBuilder.addStatement("$T $LElement = new $T()", UserTaskElement.class, literal, UserTaskElement.class);
    methodBuilder.addStatement("$LElement.setId($S)", literal, element.getId());

    BpmnElement next = element.getNext();
    if (!next.getType().isBoundaryEvent()) {
      return;
    }

    if (next.getType() == BpmnElementType.ERROR_BOUNDARY) {
      BoundaryEvent event = next.getFlowNode(BoundaryEvent.class);
      BpmnEventSupport eventSupport = new BpmnEventSupport(event);

      ErrorEventDefinition errorEventDefinition = eventSupport.getErrorDefinition();
      if (errorEventDefinition != null && errorEventDefinition.getError() != null) {
        methodBuilder.addStatement("$LElement.setErrorCode($S)", literal, errorEventDefinition.getError().getErrorCode());
      }
    }
  }
}
