package org.camunda.community.bpmndt.platform8.strategy;

import org.camunda.community.bpmndt.model.platform8.BpmnElement;
import org.camunda.community.bpmndt.model.platform8.BpmnElementType;
import org.camunda.community.bpmndt.model.platform8.BpmnEventSupport;
import org.camunda.community.bpmndt.platform8.api.TestCaseInstanceElement.UserTaskElement;

import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeName;

import io.camunda.zeebe.model.bpmn.instance.BoundaryEvent;
import io.camunda.zeebe.model.bpmn.instance.Error;
import io.camunda.zeebe.model.bpmn.instance.ErrorEventDefinition;
import io.camunda.zeebe.model.bpmn.instance.ExtensionElements;
import io.camunda.zeebe.model.bpmn.instance.UserTask;
import io.camunda.zeebe.model.bpmn.instance.zeebe.ZeebeAssignmentDefinition;
import io.camunda.zeebe.model.bpmn.instance.zeebe.ZeebeTaskSchedule;

public class UserTaskStrategy extends DefaultHandlerStrategy {

  public UserTaskStrategy(BpmnElement element) {
    super(element);
  }

  @Override
  public TypeName getHandlerType() {
    return USER_TASK;
  }

  @Override
  public void initHandler(MethodSpec.Builder methodBuilder) {
    super.initHandler(methodBuilder);

    if (!element.hasNext()) {
      return;
    }

    BpmnElement next = element.getNext();
    if (!next.getType().isBoundaryEvent()) {
      return;
    }

    if (next.getType() == BpmnElementType.ERROR_BOUNDARY) {
      methodBuilder.addStatement("$L.throwBpmnError($S)", literal, "error message, generated by BPMNDT");
    } else {
      methodBuilder.addStatement("$L.waitForBoundaryEvent()", literal);
    }
  }

  @Override
  public void initHandlerElement(MethodSpec.Builder methodBuilder) {
    methodBuilder.addCode("\n// $L: $L\n", element.getTypeName(), element.getId());
    methodBuilder.addStatement("$T $LElement = new $T()", UserTaskElement.class, literal, UserTaskElement.class);
    methodBuilder.addStatement("$LElement.setId($S)", literal, element.getId());

    UserTask userTask = element.getFlowNode(UserTask.class);
    ExtensionElements extensionElements = userTask.getExtensionElements();

    ZeebeAssignmentDefinition assignmentDefinition = (ZeebeAssignmentDefinition) extensionElements.getUniqueChildElementByType(ZeebeAssignmentDefinition.class);
    if (assignmentDefinition != null) {
      methodBuilder.addStatement("$LElement.setAssignee($S)", literal, assignmentDefinition.getAssignee());
      methodBuilder.addStatement("$LElement.setCandidateGroups($S)", literal, assignmentDefinition.getCandidateGroups());
      methodBuilder.addStatement("$LElement.setCandidateUsers($S)", literal, assignmentDefinition.getCandidateUsers());
    }

    ZeebeTaskSchedule taskSchedule = (ZeebeTaskSchedule) extensionElements.getUniqueChildElementByType(ZeebeTaskSchedule.class);
    if (taskSchedule != null) {
      methodBuilder.addStatement("$LElement.setDueDate($S)", literal, taskSchedule.getDueDate());
      methodBuilder.addStatement("$LElement.setFollowUpDate($S)", literal, taskSchedule.getFollowUpDate());
    }

    BpmnElement next = element.getNext();
    if (!next.getType().isBoundaryEvent()) {
      return;
    }

    if (next.getType() == BpmnElementType.ERROR_BOUNDARY) {
      BoundaryEvent event = next.getFlowNode(BoundaryEvent.class);
      BpmnEventSupport eventSupport = new BpmnEventSupport(event);

      ErrorEventDefinition errorEventDefinition = eventSupport.getErrorDefinition();
      if (errorEventDefinition != null) {
        Error error = errorEventDefinition.getError();
        if (error != null && error.getErrorCode() != null) {
          methodBuilder.addStatement("$LElement.setErrorCode($S)", literal, errorEventDefinition.getError().getErrorCode());
        }
      }
    }
  }
}
