plugins {
  id 'java'
  id 'org.camunda.community.bpmndt'
}

repositories {
  mavenLocal()
  mavenCentral()
}

dependencies {
  testImplementation 'io.camunda:camunda-process-test-java:8.8.16'
  testImplementation 'org.junit.jupiter:junit-jupiter-api:5.11.4'
  testImplementation 'com.google.truth:truth:1.4.5'
  testImplementation 'org.slf4j:slf4j-api:2.0.17'
  testImplementation 'org.slf4j:slf4j-reload4j:2.0.17'

  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
  testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.4'
}

compileJava {
  options.release = 21
}

test {
  useJUnitPlatform()

  testLogging {
    afterSuite { desc, result ->
      if (!desc.parent) {
        println "Tests run: ${result.testCount}, Failures: ${result.failedTestCount}, Skipped: ${result.skippedTestCount}"
      }
    }
  }
}
