name: Test
on:
  push:
    branches:
      - '**'
      - '!master'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java environment
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Run tests via Maven
        run: mvn --batch-mode clean test
